;========================================================
; JX Banner - Shared boot banner
;========================================================
; Prints system identification and serial configuration.
;
; Output:
;   JX/8080 Version x.x gSHA[+] YYMMDD.HHMM
;   SIO xx/xx RX=xx TX=xx [8251|6850] [CK=xxxx]
;
; The build stamp (commit, dirty marker, UTC build time) comes
; from ../lib/version.inc, regenerated by the Makefile on every
; build. CK is a 16-bit sum of the monitor's own image, printed
; only on ROM builds (BIOS_BASE > 0), where it answers the one
; question the version number cannot: are these the bytes I
; just built, or did the upload/burn silently not land? `make`
; prints the same value.
;
; Requires: PUTCHAR label defined by including file
; Requires: CODE_END defined by including file (ROM builds)
; Requires assembler defines:
;   VER_MAJOR, VER_MINOR, BIOS_BASE
;   SIO_DATA, SIO_STATUS, SIO_RX_MASK, SIO_TX_MASK
;   SIO_8251, SIO_6850
;========================================================

PRINT_BANNER:
        LXI     H,MSG_BAN_VER
        CALL    BAN_PRSTR
        LXI     H,MSG_BAN_BUILD
        CALL    BAN_PRSTR
        MVI     A,0DH
        CALL    PUTCHAR
        MVI     A,0AH
        CALL    PUTCHAR
        LXI     H,MSG_BAN_SIO
        CALL    BAN_PRSTR
        MVI     A,SIO_DATA
        CALL    BAN_PRHEX
        MVI     A,'/'
        CALL    PUTCHAR
        MVI     A,SIO_STATUS
        CALL    BAN_PRHEX
        LXI     H,MSG_BAN_RX
        CALL    BAN_PRSTR
        MVI     A,SIO_RX_MASK
        CALL    BAN_PRHEX
        LXI     H,MSG_BAN_TX
        CALL    BAN_PRSTR
        MVI     A,SIO_TX_MASK
        CALL    BAN_PRHEX
        IF SIO_8251
        LXI     H,MSG_BAN_8251
        CALL    BAN_PRSTR
        ENDIF
        IF SIO_6850
        LXI     H,MSG_BAN_6850
        CALL    BAN_PRSTR
        ENDIF
        IF BIOS_BASE
        LXI     H,MSG_BAN_CK
        CALL    BAN_PRSTR
        CALL    BAN_CKSUM       ; HL = sum of BIOS_BASE..CODE_END-1
        MOV     A,H
        CALL    BAN_PRHEX
        MOV     A,L
        CALL    BAN_PRHEX
        ENDIF
        MVI     A,0DH
        CALL    PUTCHAR
        MVI     A,0AH
        CALL    PUTCHAR
        RET

        IF BIOS_BASE
;--------------------------------------------------------
; BAN_CKSUM - 16-bit sum of the monitor's own image
;--------------------------------------------------------
; Sums BIOS_BASE..CODE_END-1, the code actually assembled
; into the image. The slack between CODE_END and the end of
; the ROM window is excluded, so the value does not depend
; on what a burner pads the rest of the socket with.
;
; Returns: HL = sum (mod 65536)
; Destroys: A, B, C, D, E
;--------------------------------------------------------
BAN_CKSUM:
        LXI     D,BIOS_BASE     ; Source pointer
        LXI     B,CODE_END-BIOS_BASE    ; Byte count
        LXI     H,0             ; Running sum
BAN_CKLP:
        LDAX    D
        ADD     L
        MOV     L,A
        JNC     BAN_CKNC
        INR     H               ; Carry into high byte
BAN_CKNC:
        INX     D
        DCX     B
        MOV     A,B
        ORA     C
        JNZ     BAN_CKLP
        RET
        ENDIF

;--------------------------------------------------------
; BAN_PRSTR - Print null-terminated string via PUTCHAR
;--------------------------------------------------------
BAN_PRSTR:
        MOV     A,M
        ORA     A
        RZ
        CALL    PUTCHAR
        INX     H
        JMP     BAN_PRSTR

;--------------------------------------------------------
; BAN_PRHEX - Print byte in A as two hex digits
;--------------------------------------------------------
BAN_PRHEX:
        PUSH    PSW
        RRC
        RRC
        RRC
        RRC
        CALL    BAN_PRNIB
        POP     PSW
BAN_PRNIB:
        ANI     0FH
        ADI     '0'
        CPI     '9'+1
        JC      BAN_PRN1
        ADI     'A'-'9'-1
BAN_PRN1:
        JMP     PUTCHAR

;--------------------------------------------------------
; Banner message strings
;--------------------------------------------------------
MSG_BAN_VER:
        DB      0DH,0AH
        DB      'JX/8080 Version '
        DB      '0'+VER_MAJOR,'.','0'+VER_MINOR
        DB      0                       ; build stamp follows

; MSG_BAN_BUILD - generated per build by the Makefile
        INCLUDE ../lib/version.inc

MSG_BAN_SIO:
        DB      'SIO ',0

MSG_BAN_RX:
        DB      ' RX=',0

MSG_BAN_TX:
        DB      ' TX=',0

        IF SIO_8251
MSG_BAN_8251:
        DB      ' 8251',0
        ENDIF

        IF SIO_6850
MSG_BAN_6850:
        DB      ' 6850',0
        ENDIF

        IF BIOS_BASE
MSG_BAN_CK:
        DB      '  CK=',0
        ENDIF

;========================================================
; End of banner.asm
;========================================================
